# Generated by Django 5.0.6 on 2024-06-03 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_article_alter_product_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='published',
            new_name='is_published',
        ),
    ]
