# Generated by Django 5.0.6 on 2024-06-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_rename_published_article_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='views_qty',
            field=models.PositiveIntegerField(null=True, verbose_name='Количество просмотров'),
        ),
    ]
